# fly.toml app configuration file generated for xylo-host on 2025-08-31
#
# Docs: https://fly.io/docs/reference/configuration/

app = "xylo-host"
primary_region = "iad"

[build]
  # If using Dockerfile, uncomment below:
  # dockerfile = "Dockerfile"

[env]
  SESSION_SECRET = "DI48HrMUTkSMrfqDaFoQp7ijj8CsYv6hxTjAu6j8BkAXJ578ac5wX/4PMTwEaKICcNmxuG9IECTeWuXU393TOw=="
  GITHUB_CLIENT_ID = "Ov23liodb7TKIr9E8pJc"
  GITHUB_CLIENT_SECRET = "c4579933e3d5f6fd6415978cbd474519a8e6eaf1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
